<a href="https://colab.research.google.com/github/pablocalderon9408/Data-route/blob/master/numpy_y_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Configuration and imports**

In [2]:
import numpy as np


# **Definitions: Getting started**




In [4]:
# Si bien es una matriz, sigue siendo una lista de Python
matriz = [[1,2,3], [4,5,6]]
print(type(matriz))

# Para hacer la creación de objetos de numpy, se usa la sintaxis:
np_matriz = np.array(matriz)
print(np_matriz)
print(type(np_matriz))


<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# **Indexing and Slicing**

In [10]:
# Indexación y slicing: Siempre es filas x columnas, y siempre empiezan en 0.

# Se accede al elemento de la fila 1, en la columna 2 
elemento = np_matriz[1,2]

# Slicing
matriz_recortada = np_matriz[0:1, 1:2]
print(matriz_recortada)

[[2]]


# **Tipos de datos**

##### float64, int8, string, bool

In [14]:
# Durante la creación se puede especificar el tipo de dato que va a contener.
arr = np.array([1,2,3,4,5,6,7,8,9], dtype='string_')
print(arr.dtype)

# También se puede forzar a que cambie el tipo de dato, con astype.
arr = arr.astype(np.int8)
print(arr.dtype)


|S1
int8


# **Dimensiones**
###### Escalares, Vectores, Matrices, Tensores.

In [23]:
# Con ndim se encuentra la dimensión del objeto.
dimension = arr.ndim

# Agregar o eliminar dimensiones: Se puede crear directamente con un número de dimensiones.
vector = np.array([1,2,3], ndmin=10)
print(f"Este es el vector: {vector}")

# Se puede expandir en una dirección específica. En las filas o columnas.
array = np.array([0,1,2])
print(f"Este es el array: {array}")

# Expandir en filas: axis=0
expanded_in_rows = np.expand_dims(array, axis=0)
print(f"Expandido en las filas: {expanded_in_rows}")

# Expandir en columnas: axis=1
expanded_in_cols = np.expand_dims(array, axis=1)
print(f"Expandido en las columnas: {expanded_in_cols}")

# Bajar a las dimensiones realmente utilizadas --> np.squeeze(vector)
reduced = np.squeeze(vector)
print(f"Reducción a dimensiones usadas {reduced}")



Este es el vector: [[[[[[[[[[1 2 3]]]]]]]]]]
Este es el array: [0 1 2]
Expandido en las filas: [[0 1 2]]
Expandido en las columnas: [[0]
 [1]
 [2]]
Reducción a dimensiones usadas [1 2 3]


# **Creación de arrays en Numpy**

Crear arreglos aleatorios para trabajar rápidamente.

In [42]:
# np.arange funciona como el range() de python.
np.arange(0,10)

# Crear un vector de ceros.
np.zeros(3, dtype='int8')

# Crear una matriz de ceros.
np.zeros((10,5))

# Crear matriz de unos.
np.ones((10,5))

# Crear números entre un rango, hasta una cantidad de elementos.
# Números del 0 al 500, 10 elementos.
np.linspace(0,500, 10)

# Crear una matriz de tamaño N con la diagonal en 1
np.eye(10)

# Crear una matriz con elementos en un rango, de una tamaño n x m indicado
np.random.randint(1,100, (10,5))

array([[88, 57, 80,  9, 83],
       [39, 14, 90, 15,  9],
       [72, 38,  9, 53, 84],
       [21, 35, 16, 68, 40],
       [48, 37, 83, 63, 25],
       [54, 50, 90, 79, 71],
       [16, 62, 26, 98, 61],
       [ 7, 98, 78, 53, 84],
       [96, 26,  7, 67, 62],
       [45, 58, 58, 27, 16]])

# **Shape and Reshape**

Tamaño y reajuste del tamaño de los objetos.

In [48]:
arr = np.random.randint(1,50, (7,5))
print(arr)

# The last parameter is how a language does it. C for C and F for Falcone.
# A parameter can be given and it will use the optimized way to do it in the 
# system.

# reshape in rows
np.reshape(arr, (5,7), 'C')

# reshape in columns
np.reshape(arr, (5,7), 'F')

[[ 2 20 14 19 15]
 [30 19 44 28 40]
 [14 19 29 10 25]
 [11 26 48 25 16]
 [15 24 24 16 16]
 [15  3  8 26 31]
 [ 6 36 47  5  7]]


array([[ 2, 15, 26, 44, 47, 16, 25],
       [30,  6, 24, 29, 19, 26, 16],
       [14, 20,  3, 48, 28,  5, 16],
       [11, 19, 36, 24, 10, 15, 31],
       [15, 19, 14,  8, 25, 40,  7]])

# **Common functions in numpy**

# **Copy**

When you want to slice an object, you must copy slice in order to avoid to overwrite the original one.

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
slicing = arr[0:6]
slicing

array([0, 1, 2, 3, 4, 5])

In [7]:
# When you slice an array, it stills referes in memory to the same object.
slicing[:] = 0
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [8]:
arr_2 = np.arange(0,20)
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
slice_2 = arr_2.copy()
slice_2[:10] = 10
slice_2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
# The original objects was not overwritten.
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# **Condiciones**
Conditions are used to filter arrays and to easily modify them. Lambda functions can be used.

In [14]:
arr = np.linspace(1, 10, 10, dtype="int8")
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:
# Filter by a specific condition
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [17]:
# You can use functions as well
arr = np.arange(0,15)

def number_is_even(num):
  return num % 2 == 0

number_is_even(arr)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [21]:
lambda_func = lambda x: x % 2 == 0
lambda_func(arr)


array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

# **Operaciones**

In [26]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr_2 = arr.copy()
arr_2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
1 / arr

<ipython-input-27-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [29]:
arr + arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [32]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [34]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [36]:
# Producto punto
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [37]:
# producto punto abreviado
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# **Pandas: Dataframes y series**

In [3]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [1]:
psg_players = pd.Series(
    ["Navas", "Mbappe", "Neymar", "Messi"],
    index=[1, 7, 10, 30]
)

NameError: name 'pd' is not defined