<a href="https://colab.research.google.com/github/pablocalderon9408/Data-route/blob/master/numpy_y_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Configuration and imports**

In [ ]:
import numpy as np


# **Definitions: Getting started**




In [ ]:
# Si bien es una matriz, sigue siendo una lista de Python
matriz = [[1,2,3], [4,5,6]]
print(type(matriz))

# Para hacer la creación de objetos de numpy, se usa la sintaxis:
np_matriz = np.array(matriz)
print(np_matriz)
print(type(np_matriz))


<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# **Indexing and Slicing**

In [ ]:
# Indexación y slicing: Siempre es filas x columnas, y siempre empiezan en 0.

# Se accede al elemento de la fila 1, en la columna 2 
elemento = np_matriz[1,2]

# Slicing
matriz_recortada = np_matriz[0:1, 1:2]
print(matriz_recortada)

[[2]]


# **Tipos de datos**

##### float64, int8, string, bool

In [ ]:
# Durante la creación se puede especificar el tipo de dato que va a contener.
arr = np.array([1,2,3,4,5,6,7,8,9], dtype='string_')
print(arr.dtype)

# También se puede forzar a que cambie el tipo de dato, con astype.
arr = arr.astype(np.int8)
print(arr.dtype)


|S1
int8


# **Dimensiones**
###### Escalares, Vectores, Matrices, Tensores.

In [ ]:
# Con ndim se encuentra la dimensión del objeto.
dimension = arr.ndim

# Agregar o eliminar dimensiones: Se puede crear directamente con un número de dimensiones.
vector = np.array([1,2,3], ndmin=10)
print(f"Este es el vector: {vector}")

# Se puede expandir en una dirección específica. En las filas o columnas.
array = np.array([0,1,2])
print(f"Este es el array: {array}")

# Expandir en filas: axis=0
expanded_in_rows = np.expand_dims(array, axis=0)
print(f"Expandido en las filas: {expanded_in_rows}")

# Expandir en columnas: axis=1
expanded_in_cols = np.expand_dims(array, axis=1)
print(f"Expandido en las columnas: {expanded_in_cols}")

# Bajar a las dimensiones realmente utilizadas --> np.squeeze(vector)
reduced = np.squeeze(vector)
print(f"Reducción a dimensiones usadas {reduced}")



Este es el vector: [[[[[[[[[[1 2 3]]]]]]]]]]
Este es el array: [0 1 2]
Expandido en las filas: [[0 1 2]]
Expandido en las columnas: [[0]
 [1]
 [2]]
Reducción a dimensiones usadas [1 2 3]


# **Creación de arrays en Numpy**

Crear arreglos aleatorios para trabajar rápidamente.

In [ ]:
# np.arange funciona como el range() de python.
np.arange(0,10)

# Crear un vector de ceros.
np.zeros(3, dtype='int8')

# Crear una matriz de ceros.
np.zeros((10,5))

# Crear matriz de unos.
np.ones((10,5))

# Crear números entre un rango, hasta una cantidad de elementos.
# Números del 0 al 500, 10 elementos.
np.linspace(0,500, 10)

# Crear una matriz de tamaño N con la diagonal en 1
np.eye(10)

# Crear una matriz con elementos en un rango, de una tamaño n x m indicado
np.random.randint(1,100, (10,5))

array([[88, 57, 80,  9, 83],
       [39, 14, 90, 15,  9],
       [72, 38,  9, 53, 84],
       [21, 35, 16, 68, 40],
       [48, 37, 83, 63, 25],
       [54, 50, 90, 79, 71],
       [16, 62, 26, 98, 61],
       [ 7, 98, 78, 53, 84],
       [96, 26,  7, 67, 62],
       [45, 58, 58, 27, 16]])

# **Shape and Reshape**

Tamaño y reajuste del tamaño de los objetos.

In [ ]:
arr = np.random.randint(1,50, (7,5))
print(arr)

# The last parameter is how a language does it. C for C and F for Falcone.
# A parameter can be given and it will use the optimized way to do it in the 
# system.

# reshape in rows
np.reshape(arr, (5,7), 'C')

# reshape in columns
np.reshape(arr, (5,7), 'F')

[[ 2 20 14 19 15]
 [30 19 44 28 40]
 [14 19 29 10 25]
 [11 26 48 25 16]
 [15 24 24 16 16]
 [15  3  8 26 31]
 [ 6 36 47  5  7]]


array([[ 2, 15, 26, 44, 47, 16, 25],
       [30,  6, 24, 29, 19, 26, 16],
       [14, 20,  3, 48, 28,  5, 16],
       [11, 19, 36, 24, 10, 15, 31],
       [15, 19, 14,  8, 25, 40,  7]])

# **Common functions in numpy**

# **Copy**

When you want to slice an object, you must copy slice in order to avoid to overwrite the original one.

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slicing = arr[0:6]
slicing

array([0, 1, 2, 3, 4, 5])

In [ ]:
# When you slice an array, it stills referes in memory to the same object.
slicing[:] = 0
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_2 = np.arange(0,20)
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
slice_2 = arr_2.copy()
slice_2[:10] = 10
slice_2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# The original objects was not overwritten.
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# **Condiciones**
Conditions are used to filter arrays and to easily modify them. Lambda functions can be used.

In [ ]:
arr = np.linspace(1, 10, 10, dtype="int8")
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# Filter by a specific condition
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
# You can use functions as well
arr = np.arange(0,15)

def number_is_even(num):
  return num % 2 == 0

number_is_even(arr)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [ ]:
lambda_func = lambda x: x % 2 == 0
lambda_func(arr)


array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

# **Operaciones**

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_2 = arr.copy()
arr_2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1 / arr

<ipython-input-27-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr + arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [ ]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
# Producto punto
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
# producto punto abreviado
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# **Pandas: Dataframes y series**

In [ ]:
import pandas as pd

In [ ]:
psg_players = pd.Series(
    ["Navas", "Mbappe", "Neymar", "Messi"],
    index=[1, 7, 10, 30]
)
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
psg_players_dflt= pd.Series(["Navas", 'Mbappe', 'Neymar', 'Messi'])
#si no defino los index, los indexará por defecto
psg_players_dflt

0     Navas
1    Mbappe
2    Neymar
3     Messi
dtype: object

In [ ]:
#Otra forma de definir la series de Pandas es por medio de diccionarios
dict={1:'Navas',7:'Mbappe',10:'Neymar',30:'Messi'}

In [ ]:
pd.Series(dict) #Al pandas series le enviamos como parámetro el diccionario ya definido
#Se crea la serie 
#A veces los archivos JSON tiene esa estructura de diccionario y con enviarlos al pandas series podemos reestructurarlos

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
#recordar que para ingresar a un valor, no entro por la posición ordinal sino por el indice asignado
psg_players[30]

'Messi'

In [ ]:
#Y si ahora necesito manejar un Dataframe, una estructura matricial con más datos

dict={'Jugador':["Navas", 'Mbappe', 'Neymar', 'Messi'],
      'Altura':[183.0, 170.0, 169.0, 165.0],
      'Goles':[5,200,200,200]}


In [ ]:
df_Players=pd.DataFrame(dict, index=[1,7,10,30])
#Resulta una estructura matricial indexada por filas y por columnas, es una matriz de varias dimensiones
#Esta es la estructura principal de pandas
df_Players

Jugador  Altura  Goles
1    Navas   183.0      5
7   Mbappe   170.0    200
10  Neymar   169.0    200
30   Messi   165.0    200

In [ ]:
df_Players.columns #Ver los indices a nivel de columna

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [ ]:
df_Players.index #ver indices a nivel de filas

Int64Index([1, 7, 10, 30], dtype='int64')

In [ ]:
df_books= pd.read_csv('/content/sample_data/california_housing_test.csv',sep=',', header=0)
#copio y pego la ruta del archivo
#después de indicar la ruta puedo agregar el atributo ", sep=','" para señalar cual es el separador, por default es la coma

In [ ]:
df_books

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
df_json = pd.read_json('/content/sample_data/anscombe.json')
df_json

Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

# Filtering with loc and iloc
Loc está basado en labels.
iloc

In [ ]:
df_books[["longitude", "latitude", "total_rooms"]][0:3]

longitude  latitude  total_rooms
0    -122.05     37.37       3885.0
1    -118.30     34.26       1510.0
2    -117.81     33.78       3589.0

In [ ]:
df_books.loc[:]


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
df_books.loc[0:4, ["longitude", "total_bedrooms"]]

longitude  total_bedrooms
0    -122.05           661.0
1    -118.30           310.0
2    -117.81           507.0
3    -118.36            15.0
4    -119.67           244.0

In [ ]:
df_books.loc[:, ["total_bedrooms"]]*-1

total_bedrooms
0             -661.0
1             -310.0
2             -507.0
3              -15.0
4             -244.0
...              ...
2995          -642.0
2996         -1082.0
2997          -201.0
2998           -14.0
2999          -263.0

[3000 rows x 1 columns]

In [ ]:
df_books.loc[0:4, ["total_bedrooms"]] > 50

total_bedrooms
0            True
1            True
2            True
3           False
4            True

In [ ]:
df_books.iloc[:,0:3]

longitude  latitude  housing_median_age
0       -122.05     37.37                27.0
1       -118.30     34.26                43.0
2       -117.81     33.78                27.0
3       -118.36     33.82                28.0
4       -119.67     36.33                19.0
...         ...       ...                 ...
2995    -119.86     34.42                23.0
2996    -118.14     34.06                27.0
2997    -119.70     36.30                10.0
2998    -117.12     34.10                40.0
2999    -119.63     34.42                42.0

[3000 rows x 3 columns]

# Agregar o eliminar datos con Pandas


In [ ]:
df = pd.read_csv('/content/sample_data/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]